sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_install:
  - npm install -g @angular/cli @angular/compiler-cli
install: npm install

script:
  - ng build --prod --aot

deploy:
  provider: heroku
  api_key:
    secure: $API_KEY_HEROKU
  app: task-planer
